package etsTurPom.Constants;

import org.openqa.selenium.By;

public class Constantss {
    public static By givePermission = By.id("com.etstur:id/btn_positive");
    public static By closeAdvert = By.id("com.etstur:id/collapse_button");
    public static By whereYouWanyGo = By.id("com.etstur:id/mcv1");
    public static By newFeature = By.id("com.etstur:id/btn_ok");
    public static By otelNameArea = By.id("com.etstur:id/et_input");
    public static By chooseOtelArea = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.etstur:id/rv_suggestions']/android.view.ViewGroup[7]");
    public static By fromToDates = By.id("com.etstur:id/clInput");
    public static By publicHoliday = By.xpath("//android.widget.HorizontalScrollView[@resource-id='com.etstur:id/tab_layout_calendar']/android.widget.LinearLayout/android.widget.LinearLayout[2]");
    public static By weekendHoliday = By.xpath("//android.widget.HorizontalScrollView[@resource-id='com.etstur:id/tab_layout_calendar']/android.widget.LinearLayout/android.widget.LinearLayout[3]");
    public static By calender = By.xpath("//android.widget.HorizontalScrollView[@resource-id='com.etstur:id/tab_layout_calendar']/android.widget.LinearLayout/android.widget.LinearLayout[1]");
    //public static By fromDate = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/cl_day'])[26]");
    public static By fromDate = By.xpath("//android.widget.TextView[@resource-id='com.etstur:id/tv_day' and @text='26']");
    //public static By toDate = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/cl_day'])[35]");
    public static By toDate = By.xpath("//android.widget.TextView[@resource-id='com.etstur:id/tv_day' and @text='2']");
    public static By datesTitle = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.etstur:id/calendar_view']/android.widget.FrameLayout[1]");
    public static By clearDates = By.id("com.etstur:id/btn_1");
    public static By acceptDate = By.id("com.etstur:id/btn_2");
    public static By selectPerson = By.id("com.etstur:id/cl_select_person");
    public static By adultPlus = By.xpath("(//android.widget.Button[@resource-id='com.etstur:id/btnIncrement'])[1]");
    public static By adultDecreas = By.xpath("(//android.widget.Button[@resource-id='com.etstur:id/btnDecrement'])[1]");
    public static By kidsPlus = By.xpath("(//android.widget.Button[@resource-id='com.etstur:id/btnIncrement'])[2]");
    public static By kidsDecreas = By.xpath("(//android.widget.Button[@resource-id='com.etstur:id/btnDecrement'])[2]");
    public static By kidsAge = By.id("com.etstur:id/clInput");
    public static By chooseKidsAge = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clRoot'])[4]");
    public static By acceptPerson = By.id("com.etstur:id/btn_search");
    public static By filterTxt = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.etstur:id/rv_search_result']/android.view.ViewGroup[3]");
    public static By filterBtn = By.id("com.etstur:id/cl_filter");
    public static By filterList = By.id("com.etstur:id/rv_filters");
    //public static By moreChooseFilter = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.etstur:id/rv_filters']/android.view.ViewGroup[7]");
    public static By moreChooseFilter = By.xpath("//android.widget.TextView[@resource-id='com.etstur:id/tv_title' and @text='Olanaklar']");
    public static By checkBoxBar = By.xpath("(//android.widget.CheckBox[@resource-id='com.etstur:id/cb_item'])[4]");
    public static By breakfastFilter = By.xpath("(//android.widget.CheckBox[@resource-id='com.etstur:id/cb_item'])[3]");
    public static By applyFilter = By.id("com.etstur:id/btn_apply");
    public static By sortOtels = By.id("com.etstur:id/cl_sort");
    public static By increasByPrice = By.xpath("(//android.widget.CheckBox[@resource-id='com.etstur:id/cb_sort_item'])[2]");
    public static By otelsTitle = By.id("com.etstur:id/tv_title");
    public static By chooseHotel = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/cl_amount'])[2]");
    public static By yesRoom = By.id("com.etstur:id/cl_amount");
    public static By seeRooms = By.id("com.etstur:id/btn_footer");
    public static By roomTitle = By.id("com.etstur:id/txt_room_title");
    public static By installmentLook = By.id("com.etstur:id/txt_installment_options");
    public static By cardForInstallment = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/main_constraint'])[5]");
    public static By roomDetails = By.id("com.etstur:id/btn_room_detail");
    public static By stepForPay = By.id("com.etstur:id/btn_action");
    public static By acceptRule = By.xpath("(//android.widget.CheckBox[@resource-id='com.etstur:id/cb_contract'])[3]");
    public static By myselfInfo = By.id("com.etstur:id/mcv_container");
    public static By genderMan = By.id("com.etstur:id/cb_gender_man");
    public static By genderWoman = By.id("com.etstur:id/cb_gender_woman");
    public static By namePassenger = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[1]/android.widget.EditText");
    public static By surNamePassenger = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[2]/android.widget.EditText");
    public static By mailPassenger = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[3]/android.widget.EditText");
    public static By numberPassenger = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[4]/android.widget.EditText");
    public static By nationalIdPassenger = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[5]/android.widget.EditText");
    public static By addCoupon = By.id("com.etstur:id/tv_coupon_add_header");
    public static By guestName = By.id("com.etstur:id/cl_guests");
    public static By txtCoupon = By.className("android.widget.EditText");
    public static By useCoupon = By.id("com.etstur:id/mbRight");
    public static By leaveCoupon = By.xpath("//android.widget.TextView[@text='Çıkar']");
    public static By spinnerList = By.id("com.etstur:id/cl_spinner_header");
    public static By spinnerSelect = By.id("com.etstur:id/txt");
    public static By haveErrorSpinner = By.id("com.etstur:id/btn_positive");
    public static By cardsName = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[1]/android.widget.EditText");
    public static By cardNumber = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[2]/android.widget.EditText");
    public static By cardDate = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[3]/android.widget.EditText");
    public static By cardCVV = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/clInput'])[4]/android.widget.EditText");
    public static By acceptPresentRule = By.id("com.etstur:id/cb_contract");
    public static By installmentChkBox = By.xpath("(//android.widget.CheckBox[@resource-id='com.etstur:id/checkbox'])[2]");
    public static By tryAgainPay = By.id("com.etstur:id/btn_retry");
    public static By easySendMoney = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/cl_header'])[1]");
    public static By customerNationalId = By.id("ctl00_plchldLogin_txtMusteriNoTCKN");
    public static By customerPassword = By.id("ctl00_plchldLogin_txtSifre_txtParola");
    public static By bankLogin = By.id("ctl00_plchldLogin_btnSubmit");
    public static By backPayPage = By.id("com.etstur:id/iv_back");
    //public static By dijitalWallet = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/cl_header'])[2]");
    public static By dijitalWallet = By.id("com.etstur:id/pv_digital_wallet");
    public static By juzdan = By.xpath("(//androidx.cardview.widget.CardView[@resource-id='com.etstur:id/mcv_root'])[2]/android.widget.LinearLayout/android.widget.ImageView[1]");
    //public static By payWithCredit = By.xpath("(//android.view.ViewGroup[@resource-id='com.etstur:id/cl_header'])[4]");
    public static By payWithCredit = By.id("com.etstur:id/pv_credit_payment");
    public static By payyCell = By.xpath("(//androidx.cardview.widget.CardView[@resource-id='com.etstur:id/mcv_root'])[3]/android.widget.LinearLayout/android.widget.ImageView[1]");
}
