package etsTurPom.Page;

import etsTurPom.Base.BasePage;
import io.appium.java_client.AppiumDriver;
import static etsTurPom.Constants.Constantss.*;

public class MainPage extends BasePage {

    public MainPage(AppiumDriver appiumDriver) {
        super(appiumDriver);
    }
    public MainPage mainPage(){
        //startRecordScreen();
        waitElement(givePermission);
        findElement(givePermission);
        clickElement(givePermission);
        waitElement(closeAdvert);
        findElement(closeAdvert);
        clickElement(closeAdvert);
        findElement(whereYouWanyGo);
        clickElement(whereYouWanyGo);
        findElement(newFeature);
        clickElement(newFeature);
        findElement(otelNameArea);
        sendElement(otelNameArea,"ISTANBUL");
        waitElement(chooseOtelArea);
        findElement(chooseOtelArea);
        clickElement(chooseOtelArea);
        findElement(fromToDates);
        clickElement(fromToDates);
        waitElement(publicHoliday);
        findElement(publicHoliday);
        clickElement(publicHoliday);
        waitElement(weekendHoliday);
        clickElement(weekendHoliday);
        clickElement(calender);
        waitElement(datesTitle);
        findElement(datesTitle);
        scrollScreen(456,1645,474,393);
        waitElement(fromDate);
        findElement(fromDate);
        clickElement(fromDate);
        findElement(clearDates);
        clickElement(clearDates);
        findElement(fromDate);
        clickElement(fromDate);
        clickElement(toDate);
        clickElement(acceptDate);
        findElement(selectPerson);
        clickElement(selectPerson);
        waitElement(adultPlus);
        findElement(adultPlus);
        clickElement(adultPlus);
        clickElement(adultDecreas);
        clickElement(adultDecreas);
        waitElement(kidsPlus);
        findElement(kidsPlus);
        clickElement(kidsPlus);
        findElement(kidsAge);
        clickElement(kidsAge);
        waitElement(chooseKidsAge);
        findElement(chooseKidsAge);
        clickElement(chooseKidsAge);
        clickElement(kidsDecreas);
        findElement(acceptPerson);
        clickElement(acceptPerson);
        waitElement(acceptPerson);
        findElement(acceptPerson);
        clickElement(acceptPerson);
        //stopRecordScreen();
        return this;
    }
    public MainPage searchOtels() {
        startRecordScreen();
        findElement(filterTxt);
        waitElement(filterBtn);
        findElement(filterBtn);
        clickElement(filterBtn);
        findElement(filterList);
        scrollScreen(366, 1408, 370, 994);
        waitElement(moreChooseFilter);
        findElement(moreChooseFilter);
        clickElement(moreChooseFilter);
        scrollScreen(327, 1317, 344, 788);
        findElement(checkBoxBar);
        clickElement(checkBoxBar);
        waitElement(breakfastFilter);
        findElement(breakfastFilter);
        clickElement(breakfastFilter);
        waitElement(applyFilter);
        findElement(applyFilter);
        clickElement(applyFilter);
        waitElement(sortOtels);
        findElement(sortOtels);
        clickElement(sortOtels);
        waitElement(increasByPrice);
        findElement(increasByPrice);
        clickElement(increasByPrice);
        findElement(otelsTitle);
        scrollScreen(474, 1903, 491, 60);
        findElement(yesRoom);
        clickElement(yesRoom);
        findElement(seeRooms);
        clickElement(seeRooms);
        waitElement(roomTitle);
        for (int a = 1; a <= 9; a++) {
            scrollScreen(852, 1124, 112, 1128);
        }
        findElement(installmentLook);
        clickElement(installmentLook);
        findElement(cardForInstallment);
        clickElement(cardForInstallment);
        scrollScreen(542, 284, 517, 2028);
        waitElement(roomDetails);
        findElement(roomDetails);
        clickElement(roomDetails);
        stopRecordScreen();
        return this;
    }
    public MainPage infoPassenger(){
        //startRecordScreen();
        waitElement(stepForPay);
        findElement(stepForPay);
        clickElement(stepForPay);
        findElement(acceptRule);
        clickElement(acceptRule);
        clickElement(stepForPay);
        findElement(myselfInfo);
        clickElement(myselfInfo);
        waitElement(genderMan);
        findElement(genderMan);
        clickElement(genderMan);
        clickElement(genderWoman);
        clickElement(genderMan);
        findElement(namePassenger);
        sendElement(namePassenger,"deneme");
        findElement(surNamePassenger);
        sendElement(surNamePassenger,"denemebir");
        findElement(mailPassenger);
        clickElement(mailPassenger);
        sendElementKeyboard("deneme@hotmail.com");
        scrollScreen(435,1042,443,456);
        findElement(numberPassenger);
        sendElement(numberPassenger,"5555555555");
        findElement(nationalIdPassenger);
        sendElement(nationalIdPassenger,"10000000146");
        findElement(stepForPay);
        clickElement(stepForPay);
        waitElement(stepForPay);
        findElement(stepForPay);
        clickElement(stepForPay);
        //stopRecordScreen();
        return this;
    }
    public MainPage stepPay() {
        //startRecordScreen();
        waitElement(guestName);
        scrollScreen(521, 1227, 517, 913);
        findElement(addCoupon);
        clickElement(addCoupon);
        findElement(txtCoupon);
        clickElement(txtCoupon);
        sendElementKeyboard("APPOZEL");
        findElement(useCoupon);
        clickElement(useCoupon);
        findElement(leaveCoupon);
        clickElement(leaveCoupon);
        waitElement(useCoupon);
        findElement(useCoupon);
        clickElement(useCoupon);
        waitElement(stepForPay);
        findElement(stepForPay);
        clickElement(stepForPay);
        waitElement(spinnerList);
        findElement(spinnerList);
        clickElement(spinnerList);
        findElement(spinnerSelect);
        clickElement(spinnerSelect);
        waitElement(haveErrorSpinner);
        findElement(haveErrorSpinner);
        clickElement(haveErrorSpinner);
        clickElement(spinnerList);
        scrollScreen(443, 1571, 448, 796);
        waitElement(cardsName);
        findElement(cardsName);
        sendElement(cardsName, "bonus");
        findElement(cardNumber);
        clickElement(cardNumber);
        sendElementKeyboard("5406697543211173");
        findElement(cardDate);
        clickElement(cardDate);
        sendElementKeyboard("0427");
        findElement(cardCVV);
        clickElement(cardCVV);
        sendElementKeyboard("423");
        scrollScreen(443, 1570, 456, 672);
        waitElement(installmentChkBox);
        findElement(installmentChkBox);
        clickElement(installmentChkBox);
        waitElement(acceptPresentRule);
        findElement(acceptPresentRule);
        clickElement(acceptPresentRule);
        findElement(stepForPay);
        clickElement(stepForPay);
        waitElement(tryAgainPay);
        findElement(tryAgainPay);
        clickElement(tryAgainPay);
        //stopRecordScreen();
        return this;
    }
    public MainPage otherPay(){
        //startRecordScreen();
        waitElement(easySendMoney);
        findElement(easySendMoney);
        clickElement(easySendMoney);
        findElement(acceptPresentRule);
        clickElement(acceptPresentRule);
        clickElement(stepForPay);
        findElement(backPayPage);
        clickElement(backPayPage);

        waitElement(dijitalWallet);
        findElement(dijitalWallet);
        clickElement(dijitalWallet);
        findElement(acceptPresentRule);
        clickElement(acceptPresentRule);
        findElement(juzdan);
        clickElement(juzdan);
        clickElement(dijitalWallet);
        waitElement(payWithCredit);
        findElement(payWithCredit);
        clickElement(payWithCredit);
        scrollScreen(439,1472,456,564);
        waitElement(juzdan);
        findElement(juzdan);
        clickElement(juzdan);
        findElement(stepForPay);
        clickElement(stepForPay);
        findElement(acceptPresentRule);
        clickElement(acceptPresentRule);
        clickElement(stepForPay);
        waitElement(backPayPage);
        findElement(backPayPage);
        clickElement(backPayPage);
        scrollScreen(452,1175,452,1416);
        findElement(payyCell);
        clickElement(payyCell);
        findElement(stepForPay);
        clickElement(stepForPay);
        waitElement(backPayPage);
        findElement(backPayPage);
        clickElement(backPayPage);
        //stopRecordScreen();
        return this;
    }
}
